import type { Restaurant, Driver, OptionGroup } from "./types";

// Shared option-group builders -------------------------------------------------

const drinkSize: OptionGroup = {
  id: "drink-size",
  title: "Size",
  type: "single",
  required: true,
  options: [
    { id: "sz-s", label: "Small", priceDeltaCents: 0 },
    { id: "sz-m", label: "Medium", priceDeltaCents: 100 },
    { id: "sz-l", label: "Large", priceDeltaCents: 200 },
  ],
};

const spice: OptionGroup = {
  id: "spice",
  title: "Spice level",
  type: "single",
  options: [
    { id: "sp-0", label: "Mild", priceDeltaCents: 0 },
    { id: "sp-1", label: "Medium", priceDeltaCents: 0 },
    { id: "sp-2", label: "Hot", priceDeltaCents: 0 },
    { id: "sp-3", label: "Extra hot 🔥", priceDeltaCents: 0 },
  ],
};

// Restaurants ------------------------------------------------------------------

export const RESTAURANTS: Restaurant[] = [
  {
    id: "r-midnight-slice",
    slug: "midnight-slice",
    name: "Midnight Slice",
    cuisine: "Pizza",
    tagline: "Late-night pies, done right",
    rating: 4.8,
    ratingCount: 2314,
    deliveryMinutes: 22,
    deliveryFeeCents: 199,
    priceTier: 2,
    tags: ["Trending", "Late night"],
    emoji: "🍕",
    hue: 12,
    mapPos: { x: 40, y: 235 },
    menu: [
      {
        title: "Pizzas",
        items: [
          {
            id: "d-pepperoni",
            name: "Classic Pepperoni",
            description:
              "Crisp cup-and-char pepperoni, whole-milk mozzarella, hand-crushed tomato sauce.",
            basePriceCents: 1499,
            emoji: "🍕",
            hue: 12,
            popular: true,
            optionGroups: [
              {
                id: "pz-size",
                title: "Size",
                type: "single",
                required: true,
                options: [
                  { id: "pz-10", label: '10" Personal', priceDeltaCents: 0 },
                  { id: "pz-14", label: '14" Medium', priceDeltaCents: 500 },
                  { id: "pz-18", label: '18" Large', priceDeltaCents: 900 },
                ],
              },
              {
                id: "pz-tops",
                title: "Extra toppings",
                type: "multi",
                options: [
                  { id: "t-mush", label: "Mushrooms", priceDeltaCents: 150 },
                  { id: "t-onion", label: "Red onion", priceDeltaCents: 100 },
                  { id: "t-olive", label: "Olives", priceDeltaCents: 150 },
                  { id: "t-jala", label: "Jalapeños", priceDeltaCents: 150 },
                  { id: "t-xcheese", label: "Extra cheese", priceDeltaCents: 200 },
                ],
              },
              {
                id: "pz-crust",
                title: "Crust",
                type: "single",
                options: [
                  { id: "c-hand", label: "Hand-tossed", priceDeltaCents: 0 },
                  { id: "c-thin", label: "Thin & crispy", priceDeltaCents: 0 },
                  { id: "c-stuff", label: "Stuffed crust", priceDeltaCents: 300 },
                ],
              },
            ],
          },
          {
            id: "d-margherita",
            name: "Midnight Margherita",
            description:
              "Fresh mozzarella, basil, olive oil, sea salt. Simple and perfect at 1am.",
            basePriceCents: 1399,
            emoji: "🍕",
            hue: 100,
            popular: true,
          },
          {
            id: "d-meatlovers",
            name: "The Carnivore",
            description:
              "Pepperoni, sausage, bacon, ham. For serious cravings only.",
            basePriceCents: 1799,
            emoji: "🥓",
            hue: 0,
          },
          {
            id: "d-bbqchicken",
            name: "BBQ Chicken",
            description: "Smoky BBQ sauce, grilled chicken, red onion, cilantro.",
            basePriceCents: 1699,
            emoji: "🍗",
            hue: 25,
          },
        ],
      },
      {
        title: "Sides",
        items: [
          {
            id: "d-garlicknots",
            name: "Garlic Knots (6)",
            description: "Buttery, garlicky, dusted with parmesan. Marinara for dipping.",
            basePriceCents: 599,
            emoji: "🥨",
            hue: 35,
            popular: true,
          },
          {
            id: "d-wings",
            name: "Oven Wings (8)",
            description: "Crispy wings tossed your way.",
            basePriceCents: 1099,
            emoji: "🍗",
            hue: 20,
            optionGroups: [
              {
                id: "wing-sauce",
                title: "Sauce",
                type: "single",
                required: true,
                options: [
                  { id: "ws-buff", label: "Buffalo", priceDeltaCents: 0 },
                  { id: "ws-bbq", label: "BBQ", priceDeltaCents: 0 },
                  { id: "ws-garlic", label: "Garlic parm", priceDeltaCents: 0 },
                ],
              },
              spice,
            ],
          },
          {
            id: "d-caesar",
            name: "Caesar Salad",
            description: "Romaine, croutons, shaved parm, house caesar.",
            basePriceCents: 899,
            emoji: "🥗",
            hue: 110,
          },
        ],
      },
      {
        title: "Drinks & Desserts",
        items: [
          {
            id: "d-cola",
            name: "Fountain Cola",
            description: "Ice cold, perfectly fizzy.",
            basePriceCents: 249,
            emoji: "🥤",
            hue: 350,
            optionGroups: [drinkSize],
          },
          {
            id: "d-rootbeer",
            name: "Root Beer",
            description: "Old-fashioned draft root beer.",
            basePriceCents: 279,
            emoji: "🥤",
            hue: 30,
            optionGroups: [drinkSize],
          },
          {
            id: "d-cannoli",
            name: "Cannoli (2)",
            description: "Crisp shells, sweet ricotta, chocolate chips.",
            basePriceCents: 699,
            emoji: "🍮",
            hue: 45,
          },
        ],
      },
    ],
  },
  {
    id: "r-bunbao",
    slug: "bunbao",
    name: "Bunbao",
    cuisine: "Burgers",
    tagline: "Smash burgers & golden fries",
    rating: 4.7,
    ratingCount: 1876,
    deliveryMinutes: 19,
    deliveryFeeCents: 149,
    priceTier: 2,
    tags: ["Popular", "Comfort food"],
    emoji: "🍔",
    hue: 35,
    mapPos: { x: 110, y: 170 },
    menu: [
      {
        title: "Burgers",
        items: [
          {
            id: "d-doublesmash",
            name: "Double Smash",
            description:
              "Two smashed patties, American cheese, pickles, onion, house sauce on a potato bun.",
            basePriceCents: 1199,
            emoji: "🍔",
            hue: 35,
            popular: true,
            optionGroups: [
              {
                id: "bg-addons",
                title: "Add-ons",
                type: "multi",
                options: [
                  { id: "a-bacon", label: "Bacon", priceDeltaCents: 250 },
                  { id: "a-patty", label: "Extra patty", priceDeltaCents: 300 },
                  { id: "a-avocado", label: "Avocado", priceDeltaCents: 200 },
                  { id: "a-egg", label: "Fried egg", priceDeltaCents: 175 },
                ],
              },
              {
                id: "bg-combo",
                title: "Make it a combo",
                type: "single",
                options: [
                  { id: "cb-no", label: "No thanks", priceDeltaCents: 0 },
                  { id: "cb-fries", label: "+ Fries & drink", priceDeltaCents: 449 },
                ],
              },
            ],
          },
          {
            id: "d-crispychx",
            name: "Crispy Chicken Sandwich",
            description: "Buttermilk-fried thigh, slaw, spicy mayo, pickles.",
            basePriceCents: 1099,
            emoji: "🍗",
            hue: 28,
            popular: true,
            optionGroups: [spice],
          },
          {
            id: "d-veggie",
            name: "Garden Smash",
            description: "Griddled veggie patty, cheddar, lettuce, tomato, house sauce.",
            basePriceCents: 1049,
            emoji: "🥬",
            hue: 110,
          },
        ],
      },
      {
        title: "Fries & Sides",
        items: [
          {
            id: "d-fries",
            name: "Golden Fries",
            description: "Twice-fried, sea salt. The ones you're actually craving.",
            basePriceCents: 449,
            emoji: "🍟",
            hue: 45,
            popular: true,
            optionGroups: [
              {
                id: "fr-style",
                title: "Style",
                type: "single",
                options: [
                  { id: "fs-plain", label: "Classic", priceDeltaCents: 0 },
                  { id: "fs-cheese", label: "Cheese fries", priceDeltaCents: 200 },
                  { id: "fs-loaded", label: "Loaded (bacon + ranch)", priceDeltaCents: 350 },
                ],
              },
            ],
          },
          {
            id: "d-onionrings",
            name: "Onion Rings",
            description: "Thick-cut, beer-battered, crunchy.",
            basePriceCents: 549,
            emoji: "🧅",
            hue: 40,
          },
        ],
      },
      {
        title: "Shakes & Drinks",
        items: [
          {
            id: "d-shake",
            name: "Hand-Spun Shake",
            description: "Thick, cold, made to order.",
            basePriceCents: 649,
            emoji: "🥤",
            hue: 330,
            popular: true,
            optionGroups: [
              {
                id: "shake-flavor",
                title: "Flavor",
                type: "single",
                required: true,
                options: [
                  { id: "sf-van", label: "Vanilla", priceDeltaCents: 0 },
                  { id: "sf-choc", label: "Chocolate", priceDeltaCents: 0 },
                  { id: "sf-straw", label: "Strawberry", priceDeltaCents: 0 },
                  { id: "sf-oreo", label: "Cookies & cream", priceDeltaCents: 100 },
                ],
              },
            ],
          },
          {
            id: "d-lemonade",
            name: "Fresh Lemonade",
            description: "Squeezed daily, not too sweet.",
            basePriceCents: 379,
            emoji: "🍋",
            hue: 55,
            optionGroups: [drinkSize],
          },
        ],
      },
    ],
  },
  {
    id: "r-greenbowl",
    slug: "green-bowl",
    name: "Green Bowl",
    cuisine: "Healthy",
    tagline: "Bowls that feel like a hug",
    rating: 4.6,
    ratingCount: 954,
    deliveryMinutes: 18,
    deliveryFeeCents: 99,
    priceTier: 2,
    tags: ["Healthy-ish", "Fast"],
    emoji: "🥗",
    hue: 130,
    mapPos: { x: 40, y: 105 },
    menu: [
      {
        title: "Bowls",
        items: [
          {
            id: "d-harvest",
            name: "Harvest Bowl",
            description:
              "Warm grains, roasted sweet potato, kale, apple, goat cheese, balsamic.",
            basePriceCents: 1299,
            emoji: "🥗",
            hue: 130,
            popular: true,
            optionGroups: [
              {
                id: "bowl-protein",
                title: "Protein",
                type: "single",
                options: [
                  { id: "bp-none", label: "No protein", priceDeltaCents: 0 },
                  { id: "bp-chx", label: "Grilled chicken", priceDeltaCents: 300 },
                  { id: "bp-tofu", label: "Crispy tofu", priceDeltaCents: 250 },
                  { id: "bp-salmon", label: "Roasted salmon", priceDeltaCents: 450 },
                ],
              },
              {
                id: "bowl-extras",
                title: "Extras",
                type: "multi",
                options: [
                  { id: "be-avo", label: "Avocado", priceDeltaCents: 200 },
                  { id: "be-egg", label: "Soft egg", priceDeltaCents: 150 },
                  { id: "be-nuts", label: "Toasted almonds", priceDeltaCents: 100 },
                ],
              },
            ],
          },
          {
            id: "d-burrito-bowl",
            name: "Baja Burrito Bowl",
            description: "Cilantro rice, black beans, corn salsa, cotija, chipotle crema.",
            basePriceCents: 1249,
            emoji: "🌯",
            hue: 90,
            popular: true,
            optionGroups: [spice],
          },
          {
            id: "d-pesto-pasta",
            name: "Pesto Grain Bowl",
            description: "Farro, snap peas, cherry tomato, basil pesto, parm.",
            basePriceCents: 1199,
            emoji: "🍝",
            hue: 115,
          },
        ],
      },
      {
        title: "Sides & Snacks",
        items: [
          {
            id: "d-avotoast",
            name: "Avocado Toast",
            description: "Sourdough, smashed avo, chili flake, lemon.",
            basePriceCents: 799,
            emoji: "🥑",
            hue: 100,
          },
          {
            id: "d-soup",
            name: "Tomato Basil Soup",
            description: "Slow-simmered, silky, with a hint of cream.",
            basePriceCents: 649,
            emoji: "🍲",
            hue: 10,
          },
        ],
      },
      {
        title: "Drinks",
        items: [
          {
            id: "d-smoothie",
            name: "Berry Smoothie",
            description: "Mixed berries, banana, oat milk, honey.",
            basePriceCents: 749,
            emoji: "🫐",
            hue: 280,
            popular: true,
          },
          {
            id: "d-matcha",
            name: "Iced Matcha Latte",
            description: "Ceremonial-grade matcha, your choice of milk.",
            basePriceCents: 599,
            emoji: "🍵",
            hue: 120,
            optionGroups: [drinkSize],
          },
          {
            id: "d-kombucha",
            name: "Ginger Kombucha",
            description: "Bright, fizzy, house-brewed.",
            basePriceCents: 499,
            emoji: "🫧",
            hue: 60,
          },
        ],
      },
    ],
  },
  {
    id: "r-sakura",
    slug: "sakura-express",
    name: "Sakura Express",
    cuisine: "Sushi",
    tagline: "Fresh rolls, fast",
    rating: 4.9,
    ratingCount: 1420,
    deliveryMinutes: 25,
    deliveryFeeCents: 249,
    priceTier: 3,
    tags: ["Top rated"],
    emoji: "🍣",
    hue: 340,
    mapPos: { x: 180, y: 235 },
    menu: [
      {
        title: "Rolls",
        items: [
          {
            id: "d-spicytuna",
            name: "Spicy Tuna Roll",
            description: "Fresh tuna, spicy mayo, cucumber, sesame.",
            basePriceCents: 899,
            emoji: "🍣",
            hue: 350,
            popular: true,
            optionGroups: [spice],
          },
          {
            id: "d-california",
            name: "California Roll",
            description: "Crab, avocado, cucumber, tobiko.",
            basePriceCents: 799,
            emoji: "🍣",
            hue: 25,
            popular: true,
          },
          {
            id: "d-dragon",
            name: "Dragon Roll",
            description: "Shrimp tempura, eel, avocado, unagi glaze.",
            basePriceCents: 1499,
            emoji: "🐉",
            hue: 140,
          },
          {
            id: "d-veggie-roll",
            name: "Garden Roll",
            description: "Avocado, cucumber, carrot, pickled radish.",
            basePriceCents: 699,
            emoji: "🥒",
            hue: 110,
          },
        ],
      },
      {
        title: "Plates & Sides",
        items: [
          {
            id: "d-salmonbowl",
            name: "Salmon Poke Bowl",
            description: "Sushi rice, marinated salmon, edamame, avocado, ponzu.",
            basePriceCents: 1599,
            emoji: "🍚",
            hue: 15,
            popular: true,
          },
          {
            id: "d-gyoza",
            name: "Pork Gyoza (6)",
            description: "Pan-seared, ginger-soy dipping sauce.",
            basePriceCents: 749,
            emoji: "🥟",
            hue: 35,
          },
          {
            id: "d-misosoup",
            name: "Miso Soup",
            description: "Tofu, wakame, scallion.",
            basePriceCents: 399,
            emoji: "🍲",
            hue: 40,
          },
          {
            id: "d-edamame",
            name: "Edamame",
            description: "Steamed, flaky sea salt.",
            basePriceCents: 549,
            emoji: "🫛",
            hue: 115,
          },
        ],
      },
      {
        title: "Drinks",
        items: [
          {
            id: "d-ramune",
            name: "Ramune Soda",
            description: "Classic marble-top Japanese soda.",
            basePriceCents: 449,
            emoji: "🥤",
            hue: 200,
            optionGroups: [
              {
                id: "ram-flavor",
                title: "Flavor",
                type: "single",
                required: true,
                options: [
                  { id: "rf-orig", label: "Original", priceDeltaCents: 0 },
                  { id: "rf-straw", label: "Strawberry", priceDeltaCents: 0 },
                  { id: "rf-melon", label: "Melon", priceDeltaCents: 0 },
                ],
              },
            ],
          },
          {
            id: "d-greentea",
            name: "Iced Green Tea",
            description: "Unsweetened, freshly brewed.",
            basePriceCents: 349,
            emoji: "🍵",
            hue: 120,
          },
        ],
      },
    ],
  },
  {
    id: "r-sugarhour",
    slug: "sugar-hour",
    name: "Sugar Hour",
    cuisine: "Desserts",
    tagline: "Dessert first. Dessert only.",
    rating: 4.8,
    ratingCount: 2087,
    deliveryMinutes: 20,
    deliveryFeeCents: 199,
    priceTier: 2,
    tags: ["Late night", "Sweet tooth"],
    emoji: "🍩",
    hue: 320,
    mapPos: { x: 250, y: 170 },
    menu: [
      {
        title: "Signature Sweets",
        items: [
          {
            id: "d-cookieskillet",
            name: "Cookie Skillet",
            description:
              "Warm chocolate-chip cookie baked in a skillet, vanilla ice cream on top.",
            basePriceCents: 999,
            emoji: "🍪",
            hue: 30,
            popular: true,
            optionGroups: [
              {
                id: "ck-extras",
                title: "Extras",
                type: "multi",
                options: [
                  { id: "ce-scoop", label: "Extra scoop", priceDeltaCents: 250 },
                  { id: "ce-caramel", label: "Salted caramel drizzle", priceDeltaCents: 100 },
                  { id: "ce-brownie", label: "Brownie chunks", priceDeltaCents: 150 },
                ],
              },
            ],
          },
          {
            id: "d-glazeddozen",
            name: "Glazed Donuts (6)",
            description: "Pillowy, still-warm, classic glaze.",
            basePriceCents: 899,
            emoji: "🍩",
            hue: 320,
            popular: true,
          },
          {
            id: "d-lavacake",
            name: "Molten Lava Cake",
            description: "Dark chocolate cake with a molten center, raspberry dust.",
            basePriceCents: 849,
            emoji: "🍫",
            hue: 15,
            popular: true,
          },
          {
            id: "d-cheesecake",
            name: "NY Cheesecake Slice",
            description: "Dense, creamy, graham crust, strawberry compote.",
            basePriceCents: 749,
            emoji: "🍰",
            hue: 45,
          },
          {
            id: "d-churros",
            name: "Churros (4)",
            description: "Cinnamon sugar, chocolate dipping sauce.",
            basePriceCents: 699,
            emoji: "🥖",
            hue: 30,
          },
        ],
      },
      {
        title: "Ice Cream & Shakes",
        items: [
          {
            id: "d-sundae",
            name: "Brownie Sundae",
            description: "Fudge brownie, two scoops, whipped cream, cherry.",
            basePriceCents: 899,
            emoji: "🍨",
            hue: 25,
            optionGroups: [
              {
                id: "sd-flavor",
                title: "Ice cream",
                type: "single",
                required: true,
                options: [
                  { id: "if-van", label: "Vanilla bean", priceDeltaCents: 0 },
                  { id: "if-choc", label: "Double chocolate", priceDeltaCents: 0 },
                  { id: "if-salted", label: "Salted caramel", priceDeltaCents: 50 },
                ],
              },
            ],
          },
          {
            id: "d-softserve",
            name: "Soft Serve Cone",
            description: "Vanilla, chocolate, or twist.",
            basePriceCents: 449,
            emoji: "🍦",
            hue: 45,
          },
        ],
      },
      {
        title: "Drinks",
        items: [
          {
            id: "d-hotchoc",
            name: "Thick Hot Chocolate",
            description: "European-style, practically a melted bar.",
            basePriceCents: 549,
            emoji: "☕",
            hue: 20,
            optionGroups: [drinkSize],
          },
          {
            id: "d-coldbrew",
            name: "Vanilla Cold Brew",
            description: "Slow-steeped, sweet cream float.",
            basePriceCents: 549,
            emoji: "🧋",
            hue: 35,
            optionGroups: [drinkSize],
          },
        ],
      },
    ],
  },
  {
    id: "r-casa-fuego",
    slug: "casa-fuego",
    name: "Casa Fuego",
    cuisine: "Mexican",
    tagline: "Street tacos with attitude",
    rating: 4.7,
    ratingCount: 1632,
    deliveryMinutes: 21,
    deliveryFeeCents: 149,
    priceTier: 2,
    tags: ["Trending", "Spicy"],
    emoji: "🌮",
    hue: 22,
    mapPos: { x: 110, y: 40 },
    menu: [
      {
        title: "Tacos & Mains",
        items: [
          {
            id: "d-streettacos",
            name: "Street Tacos (3)",
            description:
              "Double corn tortillas, onion, cilantro, lime. Pick your filling.",
            basePriceCents: 1099,
            emoji: "🌮",
            hue: 22,
            popular: true,
            optionGroups: [
              {
                id: "taco-fill",
                title: "Filling",
                type: "single",
                required: true,
                options: [
                  { id: "tf-pastor", label: "Al pastor", priceDeltaCents: 0 },
                  { id: "tf-carnitas", label: "Carnitas", priceDeltaCents: 0 },
                  { id: "tf-asada", label: "Carne asada", priceDeltaCents: 100 },
                  { id: "tf-mush", label: "Mushroom + poblano", priceDeltaCents: 0 },
                ],
              },
              spice,
            ],
          },
          {
            id: "d-burritogrande",
            name: "Burrito Grande",
            description:
              "Rice, beans, cheese, crema, salsa — a two-hands situation.",
            basePriceCents: 1249,
            emoji: "🌯",
            hue: 35,
            popular: true,
            optionGroups: [
              {
                id: "bur-extras",
                title: "Extras",
                type: "multi",
                options: [
                  { id: "bx-guac", label: "Guacamole", priceDeltaCents: 200 },
                  { id: "bx-queso", label: "Queso", priceDeltaCents: 150 },
                  { id: "bx-double", label: "Double meat", priceDeltaCents: 300 },
                ],
              },
              spice,
            ],
          },
          {
            id: "d-quesadilla",
            name: "Quesadilla",
            description: "Griddled flour tortilla, oaxaca cheese, salsa verde.",
            basePriceCents: 949,
            emoji: "🧀",
            hue: 45,
          },
        ],
      },
      {
        title: "Sides",
        items: [
          {
            id: "d-chipsguac",
            name: "Chips & Guac",
            description: "Warm chips, hand-mashed guacamole.",
            basePriceCents: 699,
            emoji: "🥑",
            hue: 100,
            popular: true,
          },
          {
            id: "d-elote",
            name: "Elote",
            description: "Grilled corn, crema, cotija, chile-lime dust.",
            basePriceCents: 549,
            emoji: "🌽",
            hue: 50,
          },
        ],
      },
      {
        title: "Drinks & Sweets",
        items: [
          {
            id: "d-horchata",
            name: "Horchata",
            description: "Cinnamon rice milk over ice.",
            basePriceCents: 449,
            emoji: "🥛",
            hue: 35,
            optionGroups: [drinkSize],
          },
          {
            id: "d-aguafresca",
            name: "Agua Fresca",
            description: "Watermelon or hibiscus, made daily.",
            basePriceCents: 429,
            emoji: "🍉",
            hue: 340,
            optionGroups: [drinkSize],
          },
          {
            id: "d-churrobites",
            name: "Churro Bites",
            description: "Cinnamon sugar, dulce de leche dip.",
            basePriceCents: 599,
            emoji: "🍩",
            hue: 30,
          },
        ],
      },
    ],
  },
  {
    id: "r-ronin-ramen",
    slug: "ronin-ramen",
    name: "Ronin Ramen",
    cuisine: "Ramen",
    tagline: "Broth simmered since yesterday",
    rating: 4.8,
    ratingCount: 1108,
    deliveryMinutes: 24,
    deliveryFeeCents: 199,
    priceTier: 2,
    tags: ["Cozy", "Late night"],
    emoji: "🍜",
    hue: 18,
    mapPos: { x: 180, y: 105 },
    menu: [
      {
        title: "Ramen",
        items: [
          {
            id: "d-tonkotsu",
            name: "Tonkotsu Ramen",
            description:
              "Rich pork broth, chashu, soft egg, scallion, nori.",
            basePriceCents: 1499,
            emoji: "🍜",
            hue: 18,
            popular: true,
            optionGroups: [
              {
                id: "ram-extras",
                title: "Extras",
                type: "multi",
                options: [
                  { id: "rx-chashu", label: "Extra chashu", priceDeltaCents: 300 },
                  { id: "rx-egg", label: "Extra egg", priceDeltaCents: 150 },
                  { id: "rx-corn", label: "Corn + butter", priceDeltaCents: 100 },
                  { id: "rx-noods", label: "Extra noodles", priceDeltaCents: 200 },
                ],
              },
            ],
          },
          {
            id: "d-spicymiso",
            name: "Spicy Miso Ramen",
            description: "Miso broth, chili oil, ground pork, bean sprouts.",
            basePriceCents: 1449,
            emoji: "🌶️",
            hue: 0,
            popular: true,
            optionGroups: [spice],
          },
          {
            id: "d-shoyu",
            name: "Shoyu Ramen",
            description: "Clear soy broth, chicken chashu, bamboo shoots.",
            basePriceCents: 1349,
            emoji: "🍜",
            hue: 35,
          },
        ],
      },
      {
        title: "Small Plates",
        items: [
          {
            id: "d-karaage",
            name: "Chicken Karaage",
            description: "Crispy marinated thigh, kewpie mayo, lemon.",
            basePriceCents: 849,
            emoji: "🍗",
            hue: 30,
            popular: true,
          },
          {
            id: "d-takoyaki",
            name: "Takoyaki (6)",
            description: "Octopus fritters, bonito flakes, tonkatsu drizzle.",
            basePriceCents: 799,
            emoji: "🐙",
            hue: 15,
          },
          {
            id: "d-gyoza-ronin",
            name: "Gyoza (5)",
            description: "Crispy-bottomed pork dumplings.",
            basePriceCents: 699,
            emoji: "🥟",
            hue: 40,
          },
        ],
      },
      {
        title: "Drinks & Sweets",
        items: [
          {
            id: "d-calpico",
            name: "Calpico Fizz",
            description: "Sweet-tart sparkling yogurt soda.",
            basePriceCents: 449,
            emoji: "🥤",
            hue: 200,
          },
          {
            id: "d-mochi",
            name: "Matcha Mochi (3)",
            description: "Chewy, cold, gently sweet.",
            basePriceCents: 549,
            emoji: "🍡",
            hue: 120,
          },
        ],
      },
    ],
  },
  {
    id: "r-lucky-panda",
    slug: "lucky-panda",
    name: "Lucky Panda",
    cuisine: "Chinese",
    tagline: "Takeout-box classics, extra fortune",
    rating: 4.6,
    ratingCount: 2451,
    deliveryMinutes: 20,
    deliveryFeeCents: 149,
    priceTier: 1,
    tags: ["Popular", "Family size"],
    emoji: "🥡",
    hue: 355,
    mapPos: { x: 250, y: 40 },
    menu: [
      {
        title: "Mains",
        items: [
          {
            id: "d-generaltso",
            name: "General Tso's Chicken",
            description: "Crispy chicken, sweet-hot glaze, broccoli.",
            basePriceCents: 1299,
            emoji: "🍗",
            hue: 355,
            popular: true,
            optionGroups: [spice],
          },
          {
            id: "d-beefbroccoli",
            name: "Beef & Broccoli",
            description: "Wok-seared flank steak, glossy garlic sauce.",
            basePriceCents: 1399,
            emoji: "🥦",
            hue: 120,
          },
          {
            id: "d-friedrice",
            name: "Fried Rice",
            description: "Wok-hei rice with egg and scallion.",
            basePriceCents: 999,
            emoji: "🍚",
            hue: 45,
            popular: true,
            optionGroups: [
              {
                id: "fr-protein",
                title: "Protein",
                type: "single",
                options: [
                  { id: "fp-veg", label: "Vegetable", priceDeltaCents: 0 },
                  { id: "fp-chx", label: "Chicken", priceDeltaCents: 200 },
                  { id: "fp-shrimp", label: "Shrimp", priceDeltaCents: 300 },
                ],
              },
            ],
          },
          {
            id: "d-lomein",
            name: "Lo Mein",
            description: "Soft noodles, cabbage, carrot, sesame soy.",
            basePriceCents: 1049,
            emoji: "🍝",
            hue: 35,
          },
        ],
      },
      {
        title: "Starters",
        items: [
          {
            id: "d-dumplings-lp",
            name: "Pork Dumplings (8)",
            description: "Steamed or pan-fried, black vinegar dip.",
            basePriceCents: 899,
            emoji: "🥟",
            hue: 40,
            optionGroups: [
              {
                id: "dump-style",
                title: "Style",
                type: "single",
                required: true,
                options: [
                  { id: "ds-steam", label: "Steamed", priceDeltaCents: 0 },
                  { id: "ds-fried", label: "Pan-fried", priceDeltaCents: 0 },
                ],
              },
            ],
          },
          {
            id: "d-springrolls",
            name: "Spring Rolls (3)",
            description: "Crackly veggie rolls, duck sauce.",
            basePriceCents: 549,
            emoji: "🌱",
            hue: 100,
          },
          {
            id: "d-eggdrop",
            name: "Egg Drop Soup",
            description: "Silky, golden, comforting.",
            basePriceCents: 449,
            emoji: "🥣",
            hue: 50,
          },
        ],
      },
      {
        title: "Drinks & Sweets",
        items: [
          {
            id: "d-jasminetea",
            name: "Jasmine Iced Tea",
            description: "Lightly sweetened, floral.",
            basePriceCents: 379,
            emoji: "🍵",
            hue: 90,
            optionGroups: [drinkSize],
          },
          {
            id: "d-fortunecookies",
            name: "Fortune Cookies (4)",
            description: "The dessert that talks back.",
            basePriceCents: 299,
            emoji: "🥠",
            hue: 45,
            popular: true,
          },
        ],
      },
    ],
  },
  {
    id: "r-masala-moon",
    slug: "masala-moon",
    name: "Masala Moon",
    cuisine: "Indian",
    tagline: "Curries that hug back",
    rating: 4.8,
    ratingCount: 1387,
    deliveryMinutes: 23,
    deliveryFeeCents: 199,
    priceTier: 2,
    tags: ["Top rated", "Cozy"],
    emoji: "🍛",
    hue: 32,
    mapPos: { x: 320, y: 235 },
    menu: [
      {
        title: "Curries & Mains",
        items: [
          {
            id: "d-butterchicken",
            name: "Butter Chicken",
            description:
              "Tandoori chicken in silky tomato-cream sauce, basmati rice.",
            basePriceCents: 1549,
            emoji: "🍛",
            hue: 25,
            popular: true,
            optionGroups: [spice],
          },
          {
            id: "d-chana",
            name: "Chana Masala",
            description: "Chickpeas in warm spiced tomato gravy, basmati rice.",
            basePriceCents: 1249,
            emoji: "🫘",
            hue: 35,
            optionGroups: [spice],
          },
          {
            id: "d-biryani",
            name: "Hyderabadi Biryani",
            description: "Fragrant layered rice, fried onion, raita on the side.",
            basePriceCents: 1449,
            emoji: "🍚",
            hue: 45,
            popular: true,
            optionGroups: [
              {
                id: "bir-protein",
                title: "Protein",
                type: "single",
                required: true,
                options: [
                  { id: "brp-veg", label: "Vegetable", priceDeltaCents: 0 },
                  { id: "brp-chx", label: "Chicken", priceDeltaCents: 200 },
                  { id: "brp-lamb", label: "Lamb", priceDeltaCents: 400 },
                ],
              },
              spice,
            ],
          },
          {
            id: "d-paneer",
            name: "Paneer Tikka Masala",
            description: "Charred paneer in creamy masala sauce.",
            basePriceCents: 1349,
            emoji: "🧀",
            hue: 20,
          },
        ],
      },
      {
        title: "Breads & Sides",
        items: [
          {
            id: "d-naan",
            name: "Garlic Naan",
            description: "Blistered in the tandoor, brushed with garlic butter.",
            basePriceCents: 399,
            emoji: "🫓",
            hue: 40,
            popular: true,
          },
          {
            id: "d-samosas",
            name: "Samosas (2)",
            description: "Crisp pastry, spiced potato-pea filling, chutneys.",
            basePriceCents: 549,
            emoji: "🥟",
            hue: 35,
          },
        ],
      },
      {
        title: "Drinks & Sweets",
        items: [
          {
            id: "d-mangolassi",
            name: "Mango Lassi",
            description: "Thick, cold, golden.",
            basePriceCents: 549,
            emoji: "🥭",
            hue: 40,
            popular: true,
            optionGroups: [drinkSize],
          },
          {
            id: "d-chai",
            name: "Masala Chai",
            description: "Properly spiced, properly milky.",
            basePriceCents: 429,
            emoji: "☕",
            hue: 30,
          },
          {
            id: "d-gulabjamun",
            name: "Gulab Jamun (3)",
            description: "Warm syrup-soaked dumplings, rose + cardamom.",
            basePriceCents: 499,
            emoji: "🍮",
            hue: 25,
          },
        ],
      },
    ],
  },
  {
    id: "r-cluck-house",
    slug: "cluck-house",
    name: "Cluck House",
    cuisine: "Fried Chicken",
    tagline: "Crunch you can hear from the door",
    rating: 4.7,
    ratingCount: 1965,
    deliveryMinutes: 21,
    deliveryFeeCents: 149,
    priceTier: 2,
    tags: ["Comfort food", "Crunchy"],
    emoji: "🍗",
    hue: 40,
    mapPos: { x: 320, y: 105 },
    menu: [
      {
        title: "Chicken",
        items: [
          {
            id: "d-hotsandwich",
            name: "Hot Chicken Sandwich",
            description:
              "Crispy thigh, hot oil brush, slaw, pickles, brioche.",
            basePriceCents: 1149,
            emoji: "🥪",
            hue: 15,
            popular: true,
            optionGroups: [
              {
                id: "heat",
                title: "Heat level",
                type: "single",
                required: true,
                options: [
                  { id: "h-0", label: "Country (no heat)", priceDeltaCents: 0 },
                  { id: "h-1", label: "Mild", priceDeltaCents: 0 },
                  { id: "h-2", label: "Hot", priceDeltaCents: 0 },
                  { id: "h-3", label: "Cluckin' Hot 🔥🔥", priceDeltaCents: 0 },
                ],
              },
              {
                id: "sand-combo",
                title: "Make it a combo",
                type: "single",
                options: [
                  { id: "sc-no", label: "No thanks", priceDeltaCents: 0 },
                  { id: "sc-yes", label: "+ Fries & sweet tea", priceDeltaCents: 449 },
                ],
              },
            ],
          },
          {
            id: "d-tenders",
            name: "Crispy Tenders (4)",
            description: "Buttermilk-brined, shatter-crisp crust.",
            basePriceCents: 1049,
            emoji: "🍗",
            hue: 40,
            popular: true,
            optionGroups: [
              {
                id: "tend-sauce",
                title: "Dipping sauce",
                type: "single",
                required: true,
                options: [
                  { id: "ts-honey", label: "Hot honey", priceDeltaCents: 0 },
                  { id: "ts-ranch", label: "Buttermilk ranch", priceDeltaCents: 0 },
                  { id: "ts-comeback", label: "Comeback sauce", priceDeltaCents: 0 },
                ],
              },
            ],
          },
          {
            id: "d-bucket",
            name: "Family Bucket (8 pc)",
            description: "Mixed pieces, two biscuits, pickle chips.",
            basePriceCents: 2199,
            emoji: "🪣",
            hue: 30,
          },
        ],
      },
      {
        title: "Sides",
        items: [
          {
            id: "d-maccheese",
            name: "Mac & Cheese",
            description: "Three-cheese, crispy top.",
            basePriceCents: 549,
            emoji: "🧀",
            hue: 45,
            popular: true,
          },
          {
            id: "d-biscuits",
            name: "Butter Biscuits (2)",
            description: "Flaky, with whipped honey butter.",
            basePriceCents: 449,
            emoji: "🥐",
            hue: 40,
          },
          {
            id: "d-slaw",
            name: "Coleslaw",
            description: "Cool, crunchy, just-sweet-enough.",
            basePriceCents: 399,
            emoji: "🥬",
            hue: 110,
          },
        ],
      },
      {
        title: "Drinks & Sweets",
        items: [
          {
            id: "d-sweettea",
            name: "Sweet Tea",
            description: "Southern-strength sweet.",
            basePriceCents: 349,
            emoji: "🧋",
            hue: 35,
            optionGroups: [drinkSize],
          },
          {
            id: "d-cobbler",
            name: "Peach Cobbler Cup",
            description: "Warm, jammy, buttery crumble.",
            basePriceCents: 599,
            emoji: "🍑",
            hue: 25,
          },
        ],
      },
    ],
  },
];

export const DRIVERS: Driver[] = [
  { name: "Marcus", emoji: "🧑🏾‍🦱", vehicle: "Blue e-bike", rating: 4.9 },
  { name: "Priya", emoji: "👩🏽", vehicle: "Silver scooter", rating: 4.8 },
  { name: "Tomás", emoji: "🧔🏻", vehicle: "Red hatchback", rating: 5.0 },
  { name: "Jade", emoji: "👩🏻‍🦰", vehicle: "Black motorcycle", rating: 4.9 },
  { name: "Sam", emoji: "🧑🏼", vehicle: "Green cargo bike", rating: 4.7 },
];

export function getRestaurant(slug: string): Restaurant | undefined {
  return RESTAURANTS.find((r) => r.slug === slug);
}

export function getRestaurantById(id: string): Restaurant | undefined {
  return RESTAURANTS.find((r) => r.id === id);
}

export function getDish(restaurant: Restaurant, dishId: string) {
  for (const section of restaurant.menu) {
    const dish = section.items.find((d) => d.id === dishId);
    if (dish) return dish;
  }
  return undefined;
}

export const CUISINES = [...new Set(RESTAURANTS.map((r) => r.cuisine))];
